apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}-data
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: {{ .Values.pvcScn }}
  accessModes:
    - "ReadWriteOnce"
  resources: 
    requests:
      storage: {{ .Values.pvcResources.data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}-output
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: {{ .Values.pvcScn }}
  accessModes:
    - "ReadWriteOnce"
  resources: 
    requests:
      storage: {{ .Values.pvcResources.output }}
