name: TLT Containers Weekly Builder
on:
  workflow_dispatch: # Can be manually executed
  schedule: # 1/week Sunday at 11:00PM
    - cron: "5 23 * * 0"
jobs:
  build:
    container: # MLOps Dev container for Compose Automation
      image: ${{ vars.GHA_CONTAINER_IMAGE }}
      env: # Add ENVS to control compose building
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials: # CAAS Registry Creds
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    runs-on: [aia-devops] # Runner Label
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        set-safe-directory: true
    - name: Build Container
      run: docker compose build
      working-directory: ./docker
  push:
    needs: [build]
    strategy:
      matrix:
        container: ["tlt-devel", "tlt-prod", "tlt-dist-devel", "tlt-dist-prod"] # name of Compose container
    container:
      image: ${{ vars.GHA_CONTAINER_IMAGE }}
      env: # Add ENVS to control compose building
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials: # CAAS Registry Creds
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    runs-on: [aia-devops]
    steps:
    - uses: docker/login-action@v2
      with: # CAAS Registry Creds
        registry: ${{ vars.GHA_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Push Container # tlt-<num>-<container>
      run: |
        docker tag intel/ai-tools:${{ matrix.container }}-latest ${{ vars.GHA_REGISTRY_REPO }}:ww$(date +"%U")-${{ matrix.container }}
        docker push ${{ vars.GHA_REGISTRY_REPO }}:ww$(date +"%U")-${{ matrix.container }}
