name: Build and Test docs
on:
  pull_request:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths:
      - '**'

# installs dependencies, build the docs and push it to `gh-pages`
jobs:
  docs-test:
    runs-on: [ aia-devops ]
    container:
      image: ${{ vars.GHA_IMAGE }}
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /tf_dataset/dataset/transfer_learning:/tmp/data
    steps:
    - uses: actions/checkout@v3
    # Test the docs
    - name: Run documentation tests
      run: |
        make test_docs
