name: Notebooks Test
on:
  pull_request_review:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches:
      - develop
      - main
      - r0.1
      - r0.2
      - r0.3
      - r0.4
      - r0.5
    tags:
      - '**'
    paths:
      - '**'
jobs:
  notebook-test:
    if: github.event.review.state == 'approved' ||
        github.event.pull_request.merged == true ||
        github.event_name == 'push'
    runs-on: [ aia-devops ]
    container:
      image: ${{ vars.GHA_IMAGE }}
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
        DATASET_DIR: /tmp/data
        OUTPUT_DIR: /tmp/output
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /tf_dataset/dataset/transfer_learning:/tmp/data
    steps:
      - uses: actions/checkout@v3
      - name: Run Notebook Tests
        run: make test_notebook_custom
